server:
  port: 8955
#eureka:
  #instance:
    #instance-id: ${spring.application.name}:${random.value}
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: mysql20apr2021
    username: root    
    url: jdbc:mysql://localhost:3306/employee
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update  
  #config:    #import: optional:configserver:http://localhost:8888
  application:    name: EMPLOYEE-SERVICE          
  mvc:    view:      prefix: /WEB-INF/pages/
      suffix: .jsp
  cache:    type: redis
    redis:      time-to-live: 60000
logging:  file:    name: C:/Users/SAGAR/Desktop/LogFiles/employee-service.log      
      
app:
  messages:
    saveEmployeeSuccess: EMPLOYEE CREATED
    updateEmployeeSuccess: EMPLOYEE UPDATED
    updateEmployeeNameSuccess: EMPLOYEE NAME UPDATED SUCCESSFULLY
    updateEmployeeNameError: EMPLOYEE NAME COULDN'T UPDATED
    deleteEmployeeSuccess: EMPLOYEE DELETED
  jwtSecret: SecretKey
  jwtExpirationMs: 86500000 
    
---
spring:  profiles: qa
  datasource:    url: jdbc:mysql://localhost:3306/employee_qa
server:
  port: 8956
---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/employee_prod
server:
  port: 8957
        
    
              
